### ISSUE TITLE
Upload coverage report

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibochem#24]

**Comment by TL231** [comment]
![Screenshot (4)](https://github.com/qiboteam/qibochem/assets/71241628/0fc5809a-5c44-48f2-a844-59b6549849f2)

Coverage upload sometimes fails, recommendation is to include a token (https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954) but I lack access to repo settings to create one.

**Comment by scarrazza** [comment]
Thanks @TL231, I have uploaded the token, please retry now.

**Comment by TL231** [comment]
![Screenshot (5)](https://github.com/qiboteam/qibochem/assets/71241628/927295cb-641c-4005-8392-0a3dd4dd32f9)
Token found, and it works, thanks @scarrazza.
