### ISSUE TITLE
Add sphinx documentation

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibochem#25]

**Comment by damarkian** [comment]
Done up a first draft with documentation layout on top of @chmwzc 's commit in dev/docs. Still not complete, but feel free to add/edit and commit to that branch.

**Comment by chmwzc** [comment]
Just wanted to comment that I was trying out the installation of Qibochem with PSI4 on the corporate (Windows) laptop after the change to using `poetry`. (Linux is all good, no problem)

In short, the installation failed as it was, so I made a few commits under dev/docs trying to get it to work. But still couldn't get it to work, ran into and had a discussion with damarkian in the office, and learnt that I might not need to bother with Windows at all, and so reverted the commits I made under dev/docs.
