### ISSUE TITLE
No doc deployment page

### ISSUE THREAD

**Issue by TL231** [qiboteam/qibochem#42]
As in the title, the sphinx doc deploy destination in the workflow is set to qibo.science by default but this fails with an "Error: HttpError: Not Found".
Since there aren't any differences between the publish.yml workflow and other qibo publish.yml workflows, I think it might just be because there's some setup required on that end to start accepting the doc.

**Comment by chmwzc** [comment]
I think we've resolved this after last week's meeting, right?

**Comment by TL231** [comment]
Yup, let me close the issue.
