### ISSUE TITLE
qibo version <0.2.0 requirement, while current version is 0.2.1

### ISSUE THREAD

**Issue by damarkian** [qiboteam/qibochem#49]
We may need to update qibo version requirement in poetry. It is throwing an error upon installation of e.g. qibojit:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qibochem 0.1.0 requires qibo<0.2.0,>=0.1.10, but you have qibo 0.2.1 which is incompatible.`

**Comment by TL231** [comment]
Fixed in [ec43ea1](https://github.com/qiboteam/qibochem/commit/ec43ea1cb1ea268e60824bff28da4f445198241e)
