### ISSUE TITLE
`furo` dependency

### ISSUE THREAD

**Issue by chmwzc** [qiboteam/qibochem#54]
Just wondering, I noticed that `furo` was recently included as a main dependency of `Qibochem` in `pyproject.toml`, is it really necessary?

```
[tool.poetry.dependencies]
python = ">3.9,<3.12"
qibo = ">=0.1.10"
openfermion = "^1.5"
pyscf = "2.3.0"
scipy = "^1.10.1"
furo = "^2023.09.10"
```

**Comment by TL231** [comment]
Oops, it's needed for docs but not the actual library.
I'll just remove furo from the core dependencies.
