### ISSUE TITLE
Fix release version

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibochem#60]
There is a mistmatch between the package version (__init__.py) and the pyproject.yaml version.

**Comment by scarrazza** [comment]
Reopening because #62 is not using the same approach implemented in qibo, please check how we deal with the versioning in qibo's __init__.py file. The approach in #62 is bad because it is prone to generate inconsistencies between both versions.

Moreover, please use version 0.0.1 for the time being, given that there still points to be tested and fixed (e.g. the dev documentation is not complete).

**Comment by damarkian** [comment]
Updated __init__.py and modular __init.py__ in here: https://github.com/qiboteam/qibochem/commit/b3aae212d1da998d4328709c7a0052bd9005c9e5

Used version 0.0.1 in pyproject.toml, checked using `poetry version`
