### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibochem#63]
Please update README.md by including badges and some extra information following Qibo's example.

**Comment by damarkian** [comment]
Updated here: https://github.com/qiboteam/qibochem/commit/312bffd98c36e8fd1c9986b1ee0bfb09b6249ab1

But I'm not sure if I have the correct token for codecov.

I tried to follow the same format as qibocal and qibolab. Since the zenodo badge is pending, should I update it here?

**Comment by scarrazza** [comment]
Please open a PR with the changes pointing to main.
