### ISSUE TITLE
Bug in HF embedding code

### ISSUE THREAD

**Issue by chmwzc** [qiboteam/qibochem#78]
Bug discovered while working with my Dec 2023 RAP attachment students. The following code throws an `AssertionError`:

```
from qibochem.driver import Molecule
from qibochem.ansatz import hf_circuit

# Molecule
mol = Molecule(xyz_file="../lih.xyz")
mol.run_pyscf()

mol.hf_embedding(frozen=[0, ])
```

I should have the fix already, but want to wait for #72 to be merged first.

**Comment by damarkian** [comment]
Thanks @chmwzc . I have merged #72 so please proceed.
